# Generated by Django 5.0.6 on 2024-05-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtorBack.client'),
        ),
        migrations.AddField(
            model_name='estate',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estate',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EstateOwner',
        ),
    ]
