# Generated by Django 5.0.6 on 2024-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0004_alter_estate_owner_estate_area_alter_estate_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles'),
        ),
    ]
