# Generated by Django 5.0.6 on 2024-05-24 11:56

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2006, 5, 24), message='You must be 18 y.o or older!'), django.core.validators.MinValueValidator(limit_value=datetime.date(1904, 6, 23), message='You must enter your real age!')]),
        ),
    ]
