# Generated by Django 5.0.6 on 2024-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0006_promocode_published_promocode_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars'),
        ),
    ]
