# Generated by Django 5.0.6 on 2024-05-25 16:42

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0007_remove_employee_photo_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='activated_promos',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='description',
        ),
        migrations.AddField(
            model_name='contract',
            name='activated_promo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realtorBack.promocode'),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realtorBack.estatecategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2006, 5, 25), message='You must be 18 y.o or older!'), django.core.validators.MinValueValidator(limit_value=datetime.date(1904, 6, 24), message='You must enter your real age!')]),
        ),
    ]
