# Generated by Django 5.0.6 on 2024-05-25 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0008_remove_contract_activated_promos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
