# Generated by Django 5.0.6 on 2024-05-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0009_contract_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='promo_savings',
        ),
    ]
