# Generated by Django 5.0.6 on 2024-05-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0010_remove_contract_promo_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatereview',
            name='description',
        ),
    ]
