# Generated by Django 5.0.6 on 2024-05-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorBack', '0011_remove_estatereview_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='activated_promo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtorBack.promocode'),
        ),
    ]
